# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-17 22:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_make', models.CharField(max_length=150)),
                ('car_model', models.CharField(max_length=150)),
                ('car_year', models.PositiveSmallIntegerField()),
                ('car_highway_mpg', models.PositiveSmallIntegerField()),
                ('car_city_mpg', models.PositiveSmallIntegerField()),
                ('car_combo_mpg', models.PositiveSmallIntegerField()),
                ('car_drive', models.CharField(max_length=100)),
                ('car_cylinder', models.PositiveSmallIntegerField()),
                ('car_fuel_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
