# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 04:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='car_combo_mpg',
            new_name='car_comb_mpg',
        ),
        migrations.RenameField(
            model_name='car',
            old_name='car_fuel_type',
            new_name='fuel',
        ),
    ]
