# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0002_auto_20161007_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_year',
            field=models.CharField(max_length=5),
        ),
    ]
