# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0003_auto_20161009_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
