# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-10 01:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tripapp', '0004_auto_20161110_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_year',
            field=models.CharField(max_length=5),
        ),
    ]
